filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data/fatt/log/fatt.log
  fields:
    type: Fatt
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/suricata/log/eve.json
  fields:
    type: Suricata
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/p0f/log/p0f.json
  fields:
    type: P0f
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/adbhoney/log/adbhoney.json
  fields:
    type: Adbhoney
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/ciscoasa/log/ciscoasa.log
  fields:
    type: Ciscoasa
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}

- type: log
  enabled: true
  paths:
    - /data/citrixhoneypot/logs/server.log
  fields:
    type: CitrixHoneypot
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/conpot/log/*.json
  fields:
    type: ConPot
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/cowrie/log/cowrie.json
  fields:
    type: Cowrie
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/dionaea/log/dionaea.json
  fields:
    type: Dionaea
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/dicompot/log/dicompot.log
  fields:
    type: Dicompot
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/ddospot/log/*.log
  fields:
    type: DdosPot
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}

- type: log
  enabled: true
  paths:
    - /data/elasticpot/log/elasticpot.json
  fields:
    type: ElasticPot
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/endlessh/log/endlessh.log
  fields:
    type: Endlessh
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}

- type: log
  enabled: true
  paths:
    - /data/glutton/log/glutton.log
  fields:
    type: Glutton
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}

- type: log
  enabled: true
  paths:
    - /data/hellpot/log/hellpot.log
  fields:
    type: HellPot
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/heralding/log/auth.csv
  fields:
    type: Heralding
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}

- type: log
  enabled: true
  paths:
    - /data/honeypy/log/json.log
  fields:
    type: Honeypy
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/honeysap/log/honeysap-external.log
  fields:
    type: Honeysap
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/honeytrap/log/attackers.json
  fields:
    type: Honeytrap
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/ipphoney/log/ipphoney.json
  fields:
    type: Ipphoney
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/mailoney/log/commands.log
  fields:
    type: Mailoney
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}

- type: log
  enabled: true
  paths:
    - /data/medpot/log/medpot.log
  fields:
    type: Medpot
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/rdpy/log/rdpy.log
  fields:
    type: Rdpy
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}

- type: log
  enabled: true
  paths:
    - /data/redishoneypot/log/redishoneypot.log
  fields:
    type: RedisHoneypot
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/nginx/log/access.log
  fields:
    type: NGINX
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

- type: log
  enabled: true
  paths:
    - /data/tanner/log/tanner_report.json
  fields:
    type: Tanner
    t-pot_ip_ext: ${MY_EXTIP}
    t-pot_ip_int: ${MY_INTIP}
    t-pot_hostname: ${MY_HOSTNAME}
  json.keys_under_root: true

output.logstash:
  enabled: true
  hosts: ["192.168.253.133:5044"]
  ssl.enabled: true
  ssl.verification_mode: none
  ssl.certificate_authorities: ["/etc/filebeat/rootCA.crt"]
  ssl.certificate: "/etc/filebeat/filebeat.crt"
  ssl.key: "/etc/filebeat/filebeat.key"
