filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data/fatt/log/fatt.log
  fields:
    type: Fatt

- type: log
  enabled: true
  paths:
    - /data/suricata/log/eve.json
  fields:
    type: Suricata
  json.keys_under_root: true
 
- type: log
  enabled: true
  paths:
    - /data/p0f/log/p0f.json
  fields:
    type: P0f
  json.keys_under_root: true
 
- type: log
  enabled: true
  paths:
    - /data/adbhoney/log/adbhoney.json
  fields:
    type: Adbhoney
  json.keys_under_root: true
 
- type: log
  enabled: true
  paths:
    - /data/ciscoasa/log/ciscoasa.log
  fields:
    type: Ciscoasa

- type: log
  enabled: true
  paths:
    - /data/citrixhoneypot/logs/server.log
  fields:
    type: CitrixHoneypot

- type: log
  enabled: true
  paths:
    - /data/conpot/log/*.json
  fields:
    type: ConPot
  json.keys_under_root: true
 
- type: log
  enabled: true
  paths:
    - /data/cowrie/log/cowrie.json
  fields:
    type: Cowrie
  json.keys_under_root: true
 
- type: log
  enabled: true
  paths:
    - /data/dionaea/log/dionaea.json
  fields:
    type: Dionaea
  json.keys_under_root: true
 
- type: log
  enabled: true
  paths:
    - /data/dicompot/log/dicompot.log
  fields:
    type: Dicompot

- type: log
  enabled: true
  paths:
    - /data/elasticpot/log/elasticpot.json
  fields:
    type: ElasticPot
  json.keys_under_root: true
 
- type: log
  enabled: true
  paths:
    - /data/glutton/log/glutton.log
  fields:
    type: Glutton

- type: log
  enabled: true
  paths:
    - /data/heralding/log/auth.csv
  fields:
    type: Heralding

- type: log
  enabled: true
  paths:
    - /data/honeypy/log/json.log
  fields:
    type: Honeypy

- type: log
  enabled: true
  paths:
    - /data/honeysap/log/honeysap-external.log
  fields:
    type: Honeysap

- type: log
  enabled: true
  paths:
    - /data/honeytrap/log/attackers.json
  fields:
    type: Honeytrap
  json.keys_under_root: true
 
- type: log
  enabled: true
  paths:
    - /data/ipphoney/log/ipphoney.json
  fields:
    type: Ipphoney
  json.keys_under_root: true
 
- type: log
  enabled: true
  paths:
    - /data/mailoney/log/commands.log
  fields:
    type: Mailoney

- type: log
  enabled: true
  paths:
    - /data/medpot/log/medpot.log
  fields:
    type: Medpot

- type: log
  enabled: true
  paths:
    - /data/rdpy/log/rdpy.log
  fields:
    type: Rdpy

- type: log
  enabled: true
  paths:
    - /data/nginx/log/access.log
  fields:
    type: NGINX

- type: log
  enabled: true
  paths:
    - /data/tanner/log/tanner_report.json
  fields:
    type: Tanner
  json.keys_under_root: true

processors:
  - drop_fields:
      fields: ["agent", "ecs", "log", "host", "@metadata"]
  - add_fields:
      target: host_info
      fields:
        exit_ip: "${MY_EXTIP}"
        in_ip: "${MY_INTIP}"
        hostname: "${MY_HOSTNAME}"

output.logstash:
  enabled: true
  hosts: ["<YOUR_CENTRAL_LOGSTASH_IP>:5044"]
  ssl.enabled: true
  ssl.verification_mode: none
  ssl.certificate_authorities: ["/usr/share/filebeat/rootCA.crt"]
  ssl.certificate: "/usr/share/filebeat/filebeat.crt"
  ssl.key: "/usr/share/filebeat/filebeat.key"
